services:
  backend:
    image: flask-backend
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=testing
      - SECRET_KEY=secretkey
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/testdb
      - CORS_ORIGINS=http://localhost:8080,http://localhost:5000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
